language: python
python: 2.7
sudo: false
cache:
  directories:
  - eggs
  - parts/node
env:
  - PLONE_VERSION=4.2 TEST_EGGS=buildout:test-eggs=Pillow VERSIONS=versions:collective.js.jqueryui=1.8.16.9
  - PLONE_VERSION=4.3
  - PLONE_VERSION=4.3 TEST_EGGS=buildout:test-eggs=plone.app.contenttypes
  - PLONE_VERSION=5.0
  - PLONE_VERSION=5.1
matrix:
  allow_failures:
    - env: PLONE_VERSION=4.2 TEST_EGGS=buildout:test-eggs=Pillow VERSIONS=versions:collective.js.jqueryui=1.8.16.9
    - env: PLONE_VERSION=4.3
  fast_finish: true
install:
  - sed -ie "s#4.3.x.cfg#$PLONE_VERSION.x.cfg#" buildout.cfg
  - python bootstrap.py
  - bin/buildout $TEST_EGGS $VERSIONS annotate
  - bin/buildout $TEST_EGGS $VERSIONS
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - firefox -v
script:
  - bin/code-analysis
  - bin/test
after_success:
  - bin/createcoverage -t "--layer=!Robot"
  - pip install --upgrade coveralls
  - coveralls
after_script:
# Firefox complains: GConf-WARNING **: Got Disconnected from DBus.
# And then it keeps hanging, causing a failed job after 30-50 minutes.
# So we just kill Firefox.
- pkill -9 firefox
notifications:
  irc: irc.freenode.org#plone-testing
